services:
  VideoService.server:
    image: ${DOCKER_REGISTRY-}videoservice
    build:
      context: .
      dockerfile: VideoService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=VideoServiceDB;Username=root;Password=4?H&6Gsi:33)
    ports:
      - "5004:5004"
      - "5005:5005"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: VideoServiceDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4?H&6Gsi:33)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local