# This is a generated file. Not intended for manual editing.
services:
  VideoService.server:
    build:
      context: "C:\\Users\\Daniil dev\\Desktop\\OurProject\\Streamix\\Streamix\\VideoService"
      dockerfile: "VideoService.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/VideoService.WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "videoservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\Daniil dev\\Desktop\\OurProject\\Streamix\\Streamix\\VideoService\\\
      VideoService.WebApi:/app:rw"
    - "C:\\Users\\Daniil dev\\Desktop\\OurProject\\Streamix\\Streamix\\VideoService:/src:rw"
    - "C:\\Users\\Daniil dev\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
