services:
  user.service:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Host=postgres;Database=UserDB;Username=root;Password=&Nx5$:p74K@"
    ports:
      - "5001:5001"
      - "5002:5002"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: UserDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "&Nx5$:p74K@"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local