global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using UserService.Application.Interfaces.Repositories;
global using UserService.Core.Models;
global using UserService.Infrastructure.Data;
global using UserService.Infrastructure.Identity;
global using UserService.Infrastructure.Interfaces.Repositories;